### ISSUE TITLE
cwebp-bin error on fresh install

### ISSUE THREAD

**Issue by skywickenden** [imagemin/imagemin-webp#22]
I'm getting the following error on a fresh installation.

    /path/to/root/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

imagemin-webp is implemented as follows: 

      (async () => {
        const files = await imagemin([file], outputDirectory, {
        	use: [
        		imageminWebp({quality: 90})
        	]
        });
      })();

I've triple checked that both file and outputDirectory are valid - and they work fine if I use imagemin without imageminWebp.

OS is Ubuntu 18.04. Any suggestions?

**Comment by skywickenden** [comment]
I solved this by installing the following missing libraries:

    apt-get install libglu1
    apt-get install libxi6 libgconf-2-4
    ldconfig

No idea why they are missing. This Ubuntu server is pretty vanilla.

**Comment by ncla** [comment]
Thank you, your solution helped me fix this error on local Homestead VM. Had to do the commands in this order:
```
apt-get install libglu1
apt-get install libxi6 libgconf-2-4
ldconfig
rm node_modules -rf
yarn
```

**Comment by larbisahli** [comment]
I  manage to solve this for docker container with (debian) distribution by installing the following missing libraries.

In your Dockerfile

```bash
FROM bitnami/node

RUN apt-get update && apt-get install -y libglu1 && apt-get install -y libjpeg-dev

```
Hope it helps.

**Comment by naeem1098** [comment]
> I solved this by installing the following missing libraries:
> 
> ```
> apt-get install libglu1
> apt-get install libxi6 libgconf-2-4
> ldconfig
> ```
> 
> No idea why they are missing. This Ubuntu server is pretty vanilla.

How to solve it on windows?
