### ISSUE TITLE
Imagemin API change breaks example in README

### ISSUE THREAD

**Issue by simonxabris** [imagemin/imagemin-webp#26]
Hi

With the [v7 release](https://github.com/imagemin/imagemin/releases/tag/v7.0.0) Imagemin introduced some breaking changes to the public API which means the example code in the readme no longer works.

I think the example in the readme should be updated so that it works with the latest major imagemin version or provide two examples, one for v7 and one for v6. If you think this is a good idea I'd be happy to submit a PR!

**Comment by 1000ch** [comment]
Solved by #28, very sorry for delay 🙏
