### ISSUE TITLE
Support for Converting From Binary Buffer to WEBP

### ISSUE THREAD

**Issue by Lonniebiz** [imagemin/imagemin-webp#29]
I'd like the ability to work directly with binary buffers instead of files.

I'm generating PNGs into binary buffers (instead of files) and serving that directly to the web browser via node's res.write(buffer,'binary');. I'd like to convert that buffer to webp before sending it to the web browser. I'd like to do all of this without writing files to the file system.

I see that the API returns a buffer, but don't see how I would use a binary buffer as an input argument. It seems to want the path of a file on the file system instead.

Am I over looking this in the API? If not, I'm requesting support for this.

**Comment by sindresorhus** [comment]
The API docs documents that it accepts a buffer: https://github.com/imagemin/imagemin-webp#imageminwebpoptionsbuffer

**Comment by Lonniebiz** [comment]
@sindresorhus 

Forgive me, but syntax sometimes confusing me (when it is without example). Help me look at this:
`imageminWebp(options?)(buffer)`

Does this mean, that imageninWebp is a function that also returns another function after you pass options to it? And, it is that returned function I should pass the the buffer to? Is this the correct way to interpret that?

**Comment by sindresorhus** [comment]
`imageminWebp(options?)` returns a function that accepts a buffer.
