### ISSUE TITLE
Add option to keep the original extension

### ISSUE THREAD

**Issue by szimek** [imagemin/imagemin-webp#5]
I'm trying to setup nginx to [serve webp images conditionally](https://github.com/uhop/grunt-tight-sprite/wiki/Recipe:-serve-WebP-with-nginx-conditionally) and it would be quite useful to be able to preserve the original extension, i.e.:
```
image.png -> image.png.webp
```
I can create a PR for that, but any suggestion what would be the best option name for that? `keepExtension`, `keepOriginalExtension`, `replaceExtension`?

**Comment by sindresorhus** [comment]
No thanks.

If you're using gulp you can use [`gulp-revert-path`](https://github.com/sindresorhus/gulp-revert-path) and/or `gulp-rename`.

**Comment by szimek** [comment]
@sindresorhus Thanks for the gulp-revert-path tip!
