### ISSUE TITLE
Option to keep original files

### ISSUE THREAD

**Issue by thasmo** [imagemin/imagemin-webp#7]
It would be nice to have an option so the original files won't get removed from the stream. I've been looking for a gulp plugin which would recover the files after the webp conversion but wasn't able to find something useful.

Does an option make sense, so original files are kept or is there a better way to solve this?

**Comment by shinnn** [comment]
> Does an option make sense

I don't think so. Instead, the file recovery plugin you tried should be more useful.

> is there a better way to solve this?

Support questions better go to http://stackoverflow.com/.

**Comment by sindresorhus** [comment]
Adding an option is almost never the solution. Your way, every gulp plugin would have to add an option for this. This is better done by focused gulp plugins.

https://github.com/mariocasciaro/gulp-clone
https://github.com/sindresorhus/gulp-filter
